### ISSUE TITLE
[APP REQUEST] saned - network scanner

### ISSUE THREAD

**Issue by arthurlutz** [runtipi/runtipi-appstore#1087]
Have you considered adding the app yourself? Yes

**Describe app**
Wouldn't it be great to connect your USB scanner to your tipi and have an application that enables the scanner and could be used as a network scanner or as an input to applications such as paperless-nx ? 

**Links**
Upstream : http://sane-project.org/
Example of Dockerfile (needs refresh) : https://github.com/sesceu/docker-saned/blob/master/Dockerfile 

**Additional context**
Using it over tailscale would be awesome.

**Comment by DrMxrcy** [comment]
Looking into more updated docker files 
- https://github.com/fpiesche/docker-sane
- https://github.com/sbs20/scanservjs

**Comment by arthurlutz** [comment]
Great find ! 

Indeed, later on I ended up setting up a raspberrypi3 with dietpi with portainer and scanservjs and it works great.

**Comment by DrMxrcy** [comment]
I am gonna work on adding scanservjs in then, to use in tipi!

**Comment by steveiliop56** [comment]
Hello @arthurlutz, thank you for your submission! Unfortunately I couldn't find a maintained docker version of the project so it can't be added to tipi...
