### ISSUE TITLE
[APP REQUEST] Movie-Web

### ISSUE THREAD

**Issue by n0w33d** [runtipi/runtipi-appstore#1188]
**Describe app**
A small web app for watching movies and shows easily.

**Links**
[movie-web github repo](https://github.com/movie-web/movie-web)

[movie-web self-hosting guide](https://github.com/movie-web/movie-web/blob/dev/SELFHOSTING.md)

[website](https://movie-web.app/)

[movie-web MIT license](https://github.com/movie-web/movie-web/blob/dev/LICENSE.md)

**Additional context**
This service works by displaying video files from third-party providers inside an intuitive and aesthetic user interface. No BS; just a search bar and a video player. No responsibility on the hoster, no databases or APIs hosted by the end-user, just a static site.

**Comment by DrMxrcy** [comment]
This relies on having a cloudflare service worker, Unless we can find a work around, there's not an easy one-click install
