### ISSUE TITLE
[APP REQUEST] penpot 

### ISSUE THREAD

**Issue by Daniere-Mathieu** [runtipi/runtipi-appstore#1193]
Have you considered adding the app yourself? 

**Describe app**
Penpot is a free and open source design & prototyping platform , alternative free to figma

**Links**
[penpot github](https://github.com/penpot/penpot)
[penpot website](https://penpot.app/)

**Comment by steveiliop56** [comment]
Hello @Daniere-Mathieu,

While PenPot is a good app it's extremely complicated to add. It requires about 5 containers to run. So I am looking if I there is a simple alternative to add.

**Comment by meienberger** [comment]
Thank you very much for the suggestion. Unfortunately as @steveiliop56 said, setting up Penpot is somewhat complicated and requires many manual steps like [creating users using the docker cli](https://help.penpot.app/technical-guide/getting-started/#create-users-using-cli). This will be extremely complicated to integrate in our "on click install" context. I'm closing the issue for now but if you find a solution yourself or they have updated their app to support a normal docker install flow feel free to re-open
