### ISSUE TITLE
[APP REQUEST] Urbackup

### ISSUE THREAD

**Issue by kilian-f-za** [runtipi/runtipi-appstore#1280]
Have you considered adding the app yourself? 

**Describe app**
UrBackup is an easy to setup client/server backup system, that through a combination of image and file backups accomplishes both data safety and a fast restoration time.

File and image backups are made while the system is running without interrupting current processes.

UrBackup also continuously watches folders you want backed up in order to quickly find differences to previous backups. Because of that, incremental file backups are really fast.

Your files can be restored through the web interface, via the client or the Windows Explorer while the backups of drive volumes can be restored with a bootable USB-Stick (bare metal restore).

**Links**
https://www.urbackup.org/
https://hub.docker.com/r/uroni/urbackup-server

**Additional context**
The advantage of urbackup is that there is a restore image, which makes it easier to import a backup in a complete PC crash.

**Comment by meienberger** [comment]
Hello @kilian-f-za, thanks for your suggestion. While it looks nice we already have a few backup solutions available in Tipi like Duplicati or Resilio-Sync. Our team will not invest time into adding this app but if you want to add it yourself we will be happy to review your PR and add it in our app store
