### ISSUE TITLE
[APP REQUEST] Shlink (URL Shortener)

### ISSUE THREAD

**Issue by cl3f3** [runtipi/runtipi-appstore#1293]
Have you considered adding the app yourself? 

**Describe app**
Self hosted url shortener using Docker

**Links**
https://shlink.io/
https://github.com/shlinkio/shlink

Thanks in advance

**Comment by 0livier** [comment]
ping @steveiliop56 shlink was added.

**Comment by steveiliop56** [comment]
Cool closing!
