### ISSUE TITLE
[APP REQUEST] Sunshine - Game Library Streaming

### ISSUE THREAD

**Issue by n0w33d** [runtipi/runtipi-appstore#1363]
**Description**
Sunshine is a self-hosted game stream host for Moonlight. Essentially you can play your PC games on any device that has the Moonlight app or Steam (i.e. a hacked PS Vita or hacked Nintendo Switch, or stream your Steam library to your TV, etc.). A web UI is provided to allow configuration, and client pairing, from a web browser.

**Links**
[github repo](https://github.com/LizardByte/Sunshine), [website](https://app.lizardbyte.dev/Sunshine/), [license](https://github.com/LizardByte/Sunshine/blob/nightly/LICENSE)

**Comment by steveiliop56** [comment]
Hello @n0w33d haha yes of course... You could try to add it yourself. Do you have any knowledge in docker/docker-compose? If so you can go try to add it and I am here to help for any problems or questions!
