### ISSUE TITLE
[APP REQUEST] Cloudflare Dynamic DNS

### ISSUE THREAD

**Issue by n0w33d** [runtipi/runtipi-appstore#1365]
**Describe app**
A small and robust Cloudflare dynamic IP DNS updater.

**Links**
[github repo](https://github.com/favonia/cloudflare-ddns), no website, [Apache license](https://github.com/favonia/cloudflare-ddns/blob/main/LICENSE)

**Comment by steveiliop56** [comment]
Duplicate of https://github.com/runtipi/runtipi-appstore/issues/294
