### ISSUE TITLE
[APP REQUEST] Omnivore read-it-later app

### ISSUE THREAD

**Issue by bordusko** [runtipi/runtipi-appstore#1391]
**Describe app**
Omnivore is a complete, open source read-it-later solution for people who like reading with highlighting, notes, search, and sharing capabilities.

**Links**
- [Github Repo](https://github.com/omnivore-app/omnivore)
- [Docker Compose](https://github.com/omnivore-app/omnivore/blob/main/docker-compose.yml)
- [Official website](https://omnivore.app/)

**Additional context**
Can save articles, newsletters, and documents. It's possible to sync across multiple devices with a good set of applications/extensions (IOS, MacOS, Android, Chrome, Firefox, Safari, Edge)

![image](https://github.com/runtipi/runtipi-appstore/assets/3365524/0b8ad2cc-bf02-4ee8-b380-2adaedb64772)

**Comment by meienberger** [comment]
Looks nice

**Comment by meienberger** [comment]
Hello @bordusko while your suggestion looks nice, it seems there is no official docker image available for this app and it requires a lot of manual steps to set it up. I'm closing the issue as we won't spend time to create new features just for this app. If you want to add it yourself we will be happy to review and merge your Pull Request

**Comment by bordusko** [comment]
> If you want to add it yourself we will be happy to review and merge your Pull Request

Thanks for evaluating my proposal.
I'm quite a newbie with git/docker/etc; if I'll try to do it by myself following the documentation available on Runtipi official site, do you think it's doable for a novice like me? I mean, maybe there are other apps still unsupported by Runtipi that are easier to implement in order to start practice with your system.

**Comment by meienberger** [comment]
@bordusko sure, adding an app is fairly simple in our repo. Maybe you want to take a stab at an easier one first. We have a guide [here](https://www.runtipi.io/docs/contributing/adding-a-new-app) and you can check out examples of [merged PRs](https://github.com/runtipi/runtipi-appstore/pull/1373/files) in this repo. Maybe you can try to add [Heimdall](https://hub.docker.com/r/linuxserver/heimdall/) which would be pretty easy to do. We are here to help at any step

**Comment by bordusko** [comment]
@meienberger maybe I'll try, thanks for the hints
