### ISSUE TITLE
[APP REQUEST] Personal Management System

### ISSUE THREAD

**Issue by itsrllyhim** [runtipi/runtipi-appstore#1398]
@steveiliop56 , this one's for you buddy! 

**Describe app**

It's easier to understand this web application when you think about a CMS (WordPress) or CRM (SugarCRM); the logic behind this system is very similar to those two. My PMS may offer fewer possibilities than those systems above, but it just does what I want it to do. Additionally, writing extensions is not too hard, depending on the logic required. Anyone with development knowledge can pretty much write their own extensions for personal needs. (From the maker)

**Links**
- [Official repository](https://github.com/Volmarg/personal-management-system/releases/tag/v1.4.64)
- Official docker image: **Not found**
- [Official Website](https://volmarg.github.io/)
- [Official Docker Install Guide](https://volmarg.github.io/docs/general/installation/docker/information)

**Checklist**
- [x] I have put the app name in the title of the issue
- [x] I have linked the repository of the app
- [ ] I have linked the official docker image

**Comment by itsrllyhim** [comment]
From what I can identify, this does not have an image on the docker hub. LinuxServer.io have also not created on either. Whoever takes this may have to do this themselves.

**Comment by steveiliop56** [comment]
Yeah unfortunately tipi can't build the images itself so it's not possible to add...
