### ISSUE TITLE
Gitea using ssh keys

### ISSUE THREAD

**Issue by jacobthetechy** [runtipi/runtipi-appstore#1423]
When trying to use ssh keys with Gitea and running into issues. I am not familiar enough with the project to know what the issue is. But I'm an curious if runtipi is implementing the [ssh-passthrough](https://docs.gitea.com/next/installation/install-with-docker#ssh-container-passthrough) to bypass the need to have another user on the server running runtipi?

**Comment by meienberger** [comment]
Gitea is using port 222 for SSH within tipi. If it doesn't suit you, you can try to customize your docker-compose file

**Comment by jacobthetechy** [comment]
Ok, figured out what I needed to do. The ssh url that gitea was providing was wrong. It gives `git@localhost:USER/REPO.git`. The url needs to be `ssh://git@EXPOSED_ADDRESS:222/USER/REPO.git`.

Do you happen to know what values would need to be changed in the app's config for the ssh address to be correct?

**Comment by jacobthetechy** [comment]
Found the needed config values [here!](https://forum.gitea.com/t/how-to-change-ssh-git-clone-url/7470/2)

```ini
[server]
ROOT_URL         = https://example.com
SSH_PORT         = 222
SSH_LISTEN_PORT  = 222
SSH_DOMAIN       = example.com
```

**Comment by meienberger** [comment]
Glad that you figured it out! We should probably update the App Store to include this setting no? Are you willing to contribute back your resolution?

**Comment by jacobthetechy** [comment]
That depends since the values that need to be changed are in the app.ini, See related #183. 

Are those values configurable now?

**Comment by meienberger** [comment]
Yes, I remember this file is shipped with the app

**Comment by jacobthetechy** [comment]
Is runtipi able to change those values as needed?

**Comment by meienberger** [comment]
Yes, there is a way using [template files](https://www.runtipi.io/docs/contributing/adding-a-new-app#using-a-template-in-your-data-folder) but I was thinking we could hardcode it for now as it is anyway hardcoded in the docker compose. The ideal way would be to add a environment variable for the SSH port that the user would fill in and use the template file
