### ISSUE TITLE
[APP REQUEST]

### ISSUE THREAD

**Issue by kycfree1** [runtipi/runtipi-appstore#143]
BTCPay Server.

BTCPay Server is a self-hosted, open-source cryptocurrency payment processor. It's secure, private, censorship-resistant and free.

https://btcpayserver.org/

**Comment by steveiliop56** [comment]
Hello @kycfree1, thank you for your submission! Unfortunately the app you requested does not support running on docker so it's no possible to add it to tipi...

**Comment by jacobthetechy** [comment]
@steveiliop56 would this suggest otherwise?

https://docs.btcpayserver.org/Docker/

**Comment by steveiliop56** [comment]
Also the script adds binaries to the system and etc. It's not a simple docker app... (that's why they have an image too) @meienberger what do you think?

**Comment by meienberger** [comment]
I think this is definitely possible to add as I've see this app in other system like ours. Unfortunately at the moment we don't have enough contributors to spend time ourselves adding complicated setups. If you want to try to add it yourself we will be happy to guide you and add it to the store
