### ISSUE TITLE
[APP REQUEST] MineOS

### ISSUE THREAD

**Issue by itsrllyhim** [runtipi/runtipi-appstore#1548]
May add myself but I am still working on the four I promised @steveiliop56 lol.

**Describe app**

Yes, it's another minecraft server management tool. I'm nothing if not predictable. 

**Links**
- Official repository: [Link](https://github.com/hexparrot/mineos)
- Official docker image: [Link](https://hub.docker.com/r/hexparrot/mineos)

**Checklist**
- [x] I have put the app name in the title of the issue
- [x] I have linked the repository of the app
- [x] I have linked the official docker image

**Comment by steveiliop56** [comment]
Doesn't seem it's maintained : /

**Comment by itsrllyhim** [comment]
Maintain it. 

- Supreme Commander Director

**Comment by steveiliop56** [comment]
No. (the latest commit was like in 2018)
