### ISSUE TITLE
[APP REQUEST] WordPress

### ISSUE THREAD

**Issue by Mytraas** [runtipi/runtipi-appstore#1610]
**Have you considered adding the app yourself?**

Did it: https://github.com/runtipi/runtipi-appstore/pull/1647

**Describe app**

WordPress, the versatile and powerful content management system (CMS), stands as a cornerstone in the realm of web development, providing an expansive array of tools and functionalities to cater to diverse website needs. At its core, WordPress empowers developers like you to craft websites that are not only visually appealing but also highly functional and customizable.

It could be really useful to Tippi user to install WordPress instance in one click.

**Links**
- Official repository: [https://github.com/docker-library/repo-info/tree/master/repos/wordpress](https://github.com/docker-library/repo-info/tree/master/repos/wordpress)
- Official docker image: [https://hub.docker.com/_/wordpress](https://hub.docker.com/_/wordpress)

_Usefull links:_
- [https://wordpress.org/](https://wordpress.org/)
- [https://github.com/WordPress/WordPress](https://github.com/WordPress/WordPress)

**Additional context**

Maybe we need to use MySQL:
- [https://hub.docker.com/_/mysql](https://hub.docker.com/_/mysql)
- [https://github.com/mysql/mysql-server](https://github.com/mysql/mysql-server)

**Checklist**
- [x] I have put the app name in the title of the issue
- [x] I have linked the repository of the app
- [x] I have linked the official docker image

**Comment by Mytraas** [comment]
I made a Pull Request to integrate WordPress with Tipi:  https://github.com/runtipi/runtipi-appstore/pull/1647

**Comment by steveiliop56** [comment]
Added!
