### ISSUE TITLE
🐛 [Scrypted] Missing updates

### ISSUE THREAD

**Issue by npty** [runtipi/runtipi-appstore#1771]
My Scrypted version is v0.57.0, but the update button never show up. Scrypted already published a lot of releases. https://github.com/koush/scrypted/releases

![image](https://github.com/runtipi/runtipi-appstore/assets/78221556/f369a105-a87a-40f5-8870-c3ed17d50365)

**Comment by JigSawFr** [comment]
Tags of package are a little strange and don't follow exactly semver, we need to adjust the bot on this.
Until, will udpate it manually.
