### ISSUE TITLE
🐛 [Tube Archivist] Unable to install

### ISSUE THREAD

**Issue by ghost** [runtipi/runtipi-appstore#1788]
Firstly, Tipi is amazing. I have switched from TrueNAS and I am blown away. Thank you for such great work.

I cannot get Tube Archivist to install. I have followed the link that was referenced, but that section seems to no longer exist.

**Comment by steveiliop56** [comment]
Umm closing the issue? Ghost account.

**Comment by JigSawFr** [comment]
@steveiliop56 can you confirm that you can install the app on your end without issues ? Just to know.

**Comment by banjo508** [comment]
Hello,

I am having an issue with this installation. It is refusing to connect.

Any word on this issue?
