### ISSUE TITLE
🐛 [Penpot] Bad Gateway ?

### ISSUE THREAD

**Issue by npty** [runtipi/runtipi-appstore#1982]
![image](https://github.com/runtipi/runtipi-appstore/assets/78221556/a4744844-802c-4fa5-b1ee-0c0d972df54f)

The container `penpot-backend` keep restarting every minute or so. not sure what happens, maybe it's misconfigured? 

does anyone found this issue?

**Comment by steveiliop56** [comment]
Hello @npty,

I cannot reproduce the issue. Please try reinstalling penpot and waiting some time for it to start. Closing the issue for now but if the problem persists ping me to reopen.

**Comment by JigSawFr** [comment]
Also don't forget to add logs attached, otherwise we are not able to troubleshoot
