### ISSUE TITLE
[BUG] Dozzle misconfigured after update due to removal of legacy login

### ISSUE THREAD

**Issue by DireMunchkin** [runtipi/runtipi-appstore#2154]
### Checklist
Before opening your issue be sure to have completed all those tasks.
- [x] I have searched for an already existing issue with similar context and errors. My issue has not yet been reported.
- [x] I have included a clear description and steps to reproduce.
- [x] I have included logs from the file `runtipi/logs/error.log` if relevant

**Describe the bug**
After the update to 6.x just now Dozzle will not start - This is because 5.8.1 deprecated the --login and --password options and they where removed in 6.x.

**To Reproduce**
1. Update Dozzle.
2. Container will not be accessible.
3. On the host machine `docker logs dozzle`
4. `time="2024-01-18T11:56:48Z" level=fatal msg="Using --username and --password is removed on v6.x. See https://github.com/amir20/dozzle/issues/2630 for details."`

**Additional context**
https://github.com/amir20/dozzle/issues/2630

**Comment by JigSawFr** [comment]
In fact this is expected, as upstream removed this legacy feature.

**Comment by JigSawFr** [comment]
Users facing this problem should follow upstream instructions. Without added user-config, the app still works as expected upon upgrade.

**Comment by DireMunchkin** [comment]
> Users facing this problem should follow upstream instructions. Without added user-config, the app still works as expected upon upgrade.

@JigSawFr That's not what I'm experiencing - For me Dozzle doesn't even start with the config from runtipi-appstore. How did you arrive at that?

Also all this repository is a bunch of docker configs - So if it's a misconfiguration it's a bug here IMO. I don't think you should not-fix this just because Dozzle upstream is working as intended. The Tipi app config still has issues.

**Comment by JigSawFr** [comment]
Can you share logs ? User-config ?
Will check also on my side.

**Comment by JigSawFr** [comment]
@DireMunchkin I removed login/password from env. and disabled analytics by default too.
https://github.com/runtipi/runtipi-appstore/pull/2162
To set login/password, instructions should now be followed on upstream by creating an additional file or config Authentik/Authelia

**Comment by DireMunchkin** [comment]
Thanks, I can do that.
