### ISSUE TITLE
🐛 [qBitorrent] default login credentials are incorrect 

### ISSUE THREAD

**Issue by n0w33d** [runtipi/runtipi-appstore#2159]
**Description**
The default credentials to login to qbtorrent upon a fresh install do not work. The tipi app store description says "Username: admin" and "Password: adminadmin" are both incorrect and do not work on a fresh install. 

**To Reproduce**
1. Go to 'tipi app store'
2. Click on 'qbtorrent' amd install 
3. Log in

**Expected behavior**
"admin" and "adminadmin" as stated in the description should match the login. 

**Screenshots**

![Screenshot_20240113_213403_Firefox](https://github.com/runtipi/runtipi/assets/106119998/a24c5a0e-8b31-4302-b9a4-f399f8a1ddb7)

**Server:**
 - OS: Arch
 - Tipi Version: 2.5.0

**Comment by I-Need-C8H10N4O2** [comment]
qBittorrent dropped the default password in recent builds. A random password gets generated on first run that you should be able to see in container logs. I remember when change was first introduced there was also a bug with qBittorrent where it didn't actually output the password to logs but this is probably fixed now. 

If you lost your logs, you can always modify the configuration file to change the password. If you want to set the password to the default adminadmin,  here's the relevant config:

```
 [Preferences]
WebUI\Password_PBKDF2="@ByteArray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)" 
```

**Comment by JigSawFr** [comment]
@steveiliop56 will do a check of app config before close for this

**Comment by steveiliop56** [comment]
Alright

**Comment by JigSawFr** [comment]
Confirmed, working as expected.

**Comment by steveiliop56** [comment]
Hello, the app credentials are updated. Maybe you should run ```./runtipi-cli start``` to update the repo on your system.
