### ISSUE TITLE
🐛 [Trilium] Do not bump on beta/pre-release version

### ISSUE THREAD

**Issue by avinal** [runtipi/runtipi-appstore#2169]
### Store Application

Trilium

### App version

trilium:0.63.1-beta

### Description

Apps should not be updated to `beta` release or pre-releases. In this particular case, I am trying to access Trilium notes using the Desktop application, but I get an error saying that the sync server versions are different. 
![2024-01-19T12:53:58,285588171+05:30](https://github.com/runtipi/runtipi-appstore/assets/74113200/3bdac13c-edbe-439f-88fa-ea400e57022e)

Users will always try to use the latest stable version until there is a special case. Also, the package managers (like snap, flatpak etc.) often skip pre-release versions. Users then have to manually install a beta version of client.

### Steps to reproduce

1. Install trilium client from any of the officially supported repositories.
2. Put sync config and see the error

### App logs

```bash
N/A
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of RunTipi, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by JigSawFr** [comment]
Totally agree with you, will take a look about it.
