### ISSUE TITLE
🐛 [SearXNG] OpenSearch download error in Firefox when using a Cloudflare Tunnel

### ISSUE THREAD

**Issue by jasonpearce** [runtipi/runtipi-appstore#2453]
### Store Application

SearXNG

### App version

2024.2.11

### Description

When following these (https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox) instructions on how to "Add or remove a search engine in Firefox" on a searxng.example.com domain that is WAN-exposed via Cloudflare tunnel, the browser response is:

Download Error:

> Firefox could not download the search plugin from: https://searxng.domain.com/opensearch.xml?method=POST&autocomplete=

Both SearXNG and Mozilla Firefox have documentation saying they support OpenSearch.

### Steps to reproduce

1. Build a new Ubuntu 22.04 server on a refurbished PC at home behind your firewall

2. Install RunTipi (https://runtipi.io/docs/getting-started/installation)

3. Install app Hello World as a test baseline (https://github.com/crccheck/docker-hello-world)

4. Expose the Hello World app using Cloudflare tunnels (https://runtipi.io/docs/guides/expose-apps-with-cloudflare-tunnels)

5. Validate that https://helloworld.example.com/ works externally via the Cloudflare tunnel (it does)

6. Install SearXNG (https://github.com/searxng/searxng)

7. Expose the SearXNG app using Cloudflare tunnels (https://runtipi.io/docs/guides/expose-apps-with-cloudflare-tunnels)

8. Validate that https://searxng.example.com/ works externally via the Cloudflare tunnel (it does)

9. Install Mozilla Firefox on a Windows PC

10. Using Mozilla Firefox, visit https://searxng.example.com/

11. Right-click in the Search bar that contains the https://searxng.example.com/ URL and select "Add 'SearXNG'"

12. Observe the Download Error

<img width="375" alt="image" src="https://github.com/runtipi/runtipi-appstore/assets/3466316/99db41c9-3207-4eec-a715-d3c1cd9722b0">

<img width="861" alt="image" src="https://github.com/runtipi/runtipi-appstore/assets/3466316/9d72befc-a4b7-4aab-a5b3-cc17812605e1">

### App logs

```bash
I'm not finding a way to view logs in the Tipi dashboard.
```

### Browser

Mozilla Firefox 122.0

### User-Config changes

Made no changes. 

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of RunTipi, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by meienberger** [comment]
Hello @jasonpearce thank you for the detailed issue. However, I'm not sure we can help you here as it doesn't seem to be a bug with runtipi. I would advise you to ask for help in one of the communities of searxng directly
