### ISSUE TITLE
🐛 [MinIO] No updates since addition

### ISSUE THREAD

**Issue by avinal** [runtipi/runtipi-appstore#2514]
### Store Application

Minio

### App version

RELEASE.2023-05-04T21-44-30Z

### Description

The latest version of MinIO was released about 4 days ago. https://github.com/minio/minio/releases/tag/RELEASE.2024-02-17T01-15-57Z. On checking the application configuration, it seems it was not at all updated since its addition about 8 months ago via #487

### Steps to reproduce

1. Go to apps/minio/docker-compose.yaml
2. Check the version
3. Get the latest version here ttps://github.com/minio/minio/releases/tag/RELEASE.2024-02-17T01-15-57Z and compare

### App logs

```bash
N/A
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of RunTipi, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by meienberger** [comment]
The tag format used by this image does not work with our auto-update process. I don't know if any breaking changes happened during the time since version 2023-05-04. I pushed the update, please advise if any other modification is necessary

**Comment by avinal** [comment]
Thanks, I will check and let you know.

**Comment by avinal** [comment]
Everything is working fine. No breakage with any of the integrations, so I will assume it went well.
