### ISSUE TITLE
🐛 [Home Assistant (exposed version)] Network visibility & USB mapping

### ISSUE THREAD

**Issue by alphamax** [runtipi/runtipi-appstore#2728]
### Store Application

Home Assistant

### App version

2024.3.0

### Description

Hello,

I am facing issues on my home assistant (new version) that i did not face previously.
1/ Home Assistant does not seem to see my network domotic items
2/ I have a Zigbee Sonoff Card plugged in USB and USB does not seems to be mapped.

### Steps to reproduce

Install Home Assistant
Check Hue Hub, NanoLeaf controller or anything else ==> Nothing found
Check USB card through ZHA integration ==> No connection established.
I of course try to fix by "exposing" the app in Tipi configuration. Nothing changed.

### App logs

```bash
Instead of logs I can put what i have done to fix (I am not Docker Expert, so you can imagine my personal implication to find it :p)
For the first bug, once portainer is installed, I moved the Home Assistant container to "host" network.
For the second one, i mapped manually the USB "/dev/ttyACM0".
```

### Other

FYI, there is two things to mention. Firstly on each update, config of my fix is broken and secondly it was working on the previous "non exposed" version.

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of RunTipi, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by falkheiland** [comment]
it comes down to the following settings, which were removed in order to make reverse proxy access to ha possible.

```yml
    privileged: true #2/ I have a Zigbee Sonoff Card plugged in USB and USB does not seems to be mapped.
    network_mode: host # 1/ Home Assistant does not seem to see my network domotic items
```

maybe it makes sense to reactivate the "old" homeassistant as well to the "new" homeassistant-1 app.
and then differentiate them via description:

> homeassistant: automatic discovery, local use only
> homeassistant-1: reverse proxy access

**Comment by JigSawFr** [comment]
@falkheiland @alphamax for me it's working as expected and reachable by proxy too.

Here is my custom user-config in case of:

```
services:
  mdns-repeater: #MDNS Repeater for Homekit / Homebridge usage.
    image: angelnu/mdns_repeater
    restart: unless-stopped
    network_mode: host
    environment:
    - hostNIC=eth0
    - dockerNIC=br-5813ba86106f
  matter-server: #Matter Support
    image: ghcr.io/home-assistant-libs/python-matter-server:6.1.2
    restart: unless-stopped
    network_mode: host
    security_opt:
      - "apparmor=unconfined"
    volumes:
      - /run/dbus:/run/dbus:ro
      - ${APP_DATA_DIR}/data/matter:/data
  homeassistant-1:
    dns:
      - ${DNS_IP}
    ports:
      - 21063:21063```

In fact I advise you to use Z2M instead and MQTT broker.
My setup is also with a Sonoff Dongle ;)

**Comment by JigSawFr** [comment]
I think that will provide MDNS repeater & Matter Server app too.
