### ISSUE TITLE
🐛 [netboot.xyz] "This site can’t be reached" when installing netboot.xyz after installing Cloudflare tunnel

### ISSUE THREAD

**Issue by jasonpearce** [runtipi/runtipi-appstore#2732]
### Store Application

Netboot.xyz

### App version

2.0.53

### Description

If Netboot.xyz is installed after Cloudflared, user is unable to access http://192.168.xxx.xxx:8675/ or https://192.168.xxx.xxx:8675/. Browser reports:

> This site can’t be reached
> 192.168.xxx.xxx refused to connect
> ERR_CONNECTION_REFUSED

### Steps to reproduce

1. Install Ubuntu
2. Install Tipi v3.1.0
3. Install Cloudflared v2024.2.1
4. Install Hello World
5. Validate Hello World works via http://192.168.xxx.xxx:8000/ (it does)
6. Validate Hello World works via https://helloworld.example.com (it does)
7. Install Netboot.xyz
8. Validate Netboot.xyz works via http://192.168.xxx.xxx:8675/ or https://192.168.xxx.xxx:8675/ (it does not)

### App logs

```bash
Provide instructions on how to provide logs and I'll try.
```

### Browser

Firefox and Brave

### User-Config changes

None

### Other

I have other apps that don't work if I install them after Cloudflared is installed. Some other apps, however, do work after Cloudflared is installed. I'll create separate tickets for each.

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of RunTipi, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by steveiliop56** [comment]
Hello @jasonpearce,

I can reproduce the issue. Will try to fix as soon as possible. Thank you for reporting.

**Comment by steveiliop56** [comment]
Soo after some debugging seems that there is an issue with linuxserver. For some reason the `app/` directory is empty, so there isn't anything to run. The only possible solution I can think of is to move to the official docker-netbootxyz image. @meienberger what do you think?

**Comment by meienberger** [comment]
Sounds good for me @steveiliop56 is there any bug report on their repo? Did we do something wrong?

**Comment by jasonpearce** [comment]
After upgrading to...

- RunTipi v3.1.3
- Cloudflared v2024.3.0
- Netboot.xyz v2.0.53

My results are unchanged:

- Netboot by IP (http/https) on port 8675 is Unable to connect
- Hello World still works by local IP and via the Cloudflare tunnel

**Comment by steveiliop56** [comment]
I will try to release an update today.

**Comment by steveiliop56** [comment]
Hello,

This has been fixed now. Sorry for the massive delay

**Comment by JigSawFr** [comment]
@steveiliop56 what was the fix ?

**Comment by steveiliop56** [comment]
I just changed the image from the Linux server to the official one (paths are the same so not data loss).

**Comment by JigSawFr** [comment]
> I just changed the image from the Linux server to the official one (paths are the same so not data loss).

Ok just that lol was thinking it will be harder for this case

**Comment by jasonpearce** [comment]
On my node, I verify this issue is resolved.

- Netboot.xyz version 0.7.1-nbxyz3
- Cloudflard version 2024.6.1
- RunTipi version 3.4.1

Thank you.
