### ISSUE TITLE
Cloudflare-ddns

### ISSUE THREAD

**Issue by RobotsAreCrazy** [runtipi/runtipi-appstore#294]
Any chance of you adding this docker for keeping ip synced if someone doesn't have a dedicated isp provided IP and they use cloudflare for domains etc?Thanks

**Comment by DrMxrcy** [comment]
Hello! Yes I am looking into adding one. Probaly will use https://github.com/favonia/cloudflare-ddns to manage it via the UI.

I also have seen https://github.com/timothymiller/cloudflare-ddns which has a little more flexibility, but its managed via a json file, and we can not edit files within the UI atm.
