### ISSUE TITLE
🐛 [Flaresolverr] Not working

### ISSUE THREAD

**Issue by williambout** [runtipi/runtipi-appstore#3041]
### Store Application

Flaresolverr

### App version

3.3.16

### Description

Not sure if the docker compose is up to date, but app doesn't seem to be accessible on the default port.

### Steps to reproduce

1. Install Flaresolverr

### App logs

```bash
-
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of RunTipi, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by JigSawFr** [comment]
Are you sure on this matter @williambout ? Flaresolverr doesn't have GUI, it only accept API requests

**Comment by JigSawFr** [comment]
Tried on my side and confirmed that works as expected with Prowlarr at least.

![image](https://github.com/runtipi/runtipi-appstore/assets/5781907/361c7eec-6ecd-4d4d-aff1-2c73334bca73)

**Comment by williambout** [comment]
@JigSawFr Thanks! I was using the wrong port, I just opened a PR with the correct default value. https://github.com/runtipi/runtipi-appstore/pull/3042

**Comment by cmolina** [comment]
I am confused, where is the port `8191` coming from?

I was trying to [test it as instructed in their readme](https://github.com/FlareSolverr/FlareSolverr?tab=readme-ov-file#usage), by ssh-ing to my server and running

```shell
$ curl -L -X POST 'http://localhost:8191/v1' \
-H 'Content-Type: application/json' \
--data-raw '{
  "cmd": "request.get",
  "url": "http://www.google.com/",
  "maxTimeout": 60000
}'
```

But I am getting this error: `curl: (7) Failed to connect to localhost port 8191 after 0 ms: Connection refused`. I get the same error when using port `8666`. 

Why can't I access flaresolverr from my terminal?
