### ISSUE TITLE
[APP REQUEST] trashcan

### ISSUE THREAD

**Issue by innocentius** [runtipi/runtipi-appstore#314]
Have you considered adding the app yourself? 
(Yes, but I don't have the time...)

**Describe app**
`trashcan` -- web based service for indexing scientific papers (or any other documents)

Features:

* Single lightweight backend service written in C++ using SQLite database.
* Single page web interface. PDF files can be preview in the same browser window.
* Documents metadata can be fetched using DOI, ArXiv or ISBN (using Google Books) identifiers.
* Documents can be categorized using user-defined tags.
* Full-text search support. Documents contents is extracted with Apache Tika and indexed using SQLite FTS.

**Links**
https://gitlab.com/mildlyparallel/trashcan

**Additional context**
Add any other context or screenshots about the app request here.

**Comment by steveiliop56** [comment]
Hello @innocentius, thank you for your submission! Unfortunately this app requires building the docker image something that tipi can't do at the moment...
