### ISSUE TITLE
[APP REQUEST] Jitsi Meet

### ISSUE THREAD

**Issue by RasheedAZ** [runtipi/runtipi-appstore#316]
Have you considered adding the app yourself? 
Yes but looks like it's above my ability I'm afraid.

**Describe app**
Jitsi Meet is a fully encrypted, 100% Open Source video conferencing solution that you can use all day, every day, for free — with no account needed. It is widely regarded as the best privacy-respecting alternative to Zoom.

**Links**
Github repo: https://github.com/jitsi/docker-jitsi-meet
Website: https://jitsi.org/jitsi-meet/
Demo: https://meet.jit.si
License: https://github.com/jitsi/docker-jitsi-meet/blob/master/LICENSE
Docker installation: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker/

**Additional context**
Screenshots: 
![readme-img1](https://user-images.githubusercontent.com/16827461/231437898-4f2c8ee4-fec6-4e8c-bedb-f6096e0beb09.png)
![blog-whiteboard-1](https://user-images.githubusercontent.com/16827461/231437934-1c9bed0c-1093-4a2f-a878-cf18c160b64c.png)

**Comment by Nurullaev** [comment]
Добрый день. Поддерживаю. Очень нужно данное приложение

**Comment by steveiliop56** [comment]
Hello @RasheedAZ, thank you for your submission! Unfortunately this app requires running custom commands before the docker-compose file something tipi can't do for now...

**Comment by steveiliop56** [comment]
Oh then we need to reopen a lot of issues...
