### ISSUE TITLE
[APP REQUEST] Pleroma

### ISSUE THREAD

**Issue by innocentius** [runtipi/runtipi-appstore#338]
Have you considered adding the app yourself? 
Yes.

**Describe app**
[Pleroma](https://pleroma.social/) is a federated social networking platform, compatible with GNU social and other OStatus implementations. It is free software licensed under the AGPLv3.

This is basically a easier, light-weight version of mastodon, and it should serve greatly as a self-hosted, decentralized social media plataform. 

**Links**
https://github.com/angristan/docker-pleroma

**Additional context**
Add any other context or screenshots about the app request here.

**Comment by DrMxrcy** [comment]
This is on my To-Do List. Going to add Mastodon as well down the line.

**Comment by steveiliop56** [comment]
Hello @innocentius, thank you for your submission! Unfortunately the docker image doesn't seem to be maintained anymore...
