### ISSUE TITLE
[APP REQUEST] Pretalx

### ISSUE THREAD

**Issue by Lukas2112** [runtipi/runtipi-appstore#34]
**Describe app**
> *"Conference planning tool: CfP, scheduling, speaker management"* (Description from the github repo)

This software can be used to create plans for conferences.

**Links**
GitHub: https://github.com/pretalx/pretalx
Project page: https://pretalx.com/
Documentation: https://docs.pretalx.org/

**Additional context**
Add any other context or screenshots about the app request here.

**Comment by steveiliop56** [comment]
It doesn't have neither a dockerfile nor a docker compose file.
