### ISSUE TITLE
🐛 [Mealie] No updates since addition

### ISSUE THREAD

**Issue by tsagadar** [runtipi/runtipi-appstore#3432]
### Store Application

Mealie

### App version

v1.0.0-RC2

### Description

The latest version of Mealie was released yesterday. https://github.com/mealie-recipes/mealie/releases/tag/v1.6.0. On checking the application configuration, it seems it was not at all updated since its addition about 4 months ago.

Looking through the release notes I don't see any breaking changes between v1.0.0-RC2 and v1.6.0.

### Steps to reproduce

1. Go to apps/mealie/docker-compose.yaml
2. Check the version
3. Get the latest version here https://github.com/mealie-recipes/mealie/releases/tag/v1.6.0 and compare

### App logs

```bash
n/a
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of RunTipi, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by MontejoJorge** [comment]
Dont know how renovate bot works, but seems like it hasn't detected the updates
