### ISSUE TITLE
[APP REQUEST] Engelsystem

### ISSUE THREAD

**Issue by Lukas2112** [runtipi/runtipi-appstore#35]
**Describe app**
>*"Shift planning system for chaos events."* (GitHub repo description)

This software makes it possible to organise people for events, for example at trade fairs.

**Links**
Source code: https://github.com/engelsystem/engelsystem
Project page: https://engelsystem.de/en

**Additional context**
Add any other context or screenshots about the app request here.

**Comment by steveiliop56** [comment]
They don't have an image, they require you to build it... Tipi can't do that...
