### ISSUE TITLE
🐛 [MyApp] Current version used for Tailscale has a known security vulnerability

### ISSUE THREAD

**Issue by dbjones-clanjones** [runtipi/runtipi-appstore#3534]
### Store Application

Tailscale

### App version

1.64.2

### Description

Tailscale flags all instances of a Linux machine running 1.64.2 as follows "This machine is running a version with a known security vulnerability. It’s recommended to update to 1.66.4."

Can Tailscale be updated to this latest version please?

### Steps to reproduce

Issue as showing in the Tailscale's Machine List:

### App logs

```bash
Not applicable
```

### Browser

Any

### User-Config changes

![image](https://github.com/runtipi/runtipi-appstore/assets/97272092/68c7a379-4f04-450a-8aeb-965054a8daff)

### Other

Update Tailscale to the latest version.

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of RunTipi, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by cori** [comment]
I believe this has been [resolved](https://github.com/runtipi/runtipi-appstore/pull/3605).

**Comment by JigSawFr** [comment]
@cori totally, docker releases of tailscale are a bit delayed, don't know why :)
