### ISSUE TITLE
[APP REQUEST] Zammad

### ISSUE THREAD

**Issue by Lukas2112** [runtipi/runtipi-appstore#36]
**Describe app**
> *"Zammad is a free helpdesk and issue tracking system. It offers the connection of various channels such as email, chat, telephone, Twitter or Facebook."* 

A ticket system, in this case even with integrated knowledge management, would take a lot of mangement away from the runtipi users.

**Links**
Zammad Professional Services: https://zammad.com/
Zammad Community: https://zammad.org/
Zammad Foundation: http://zammad-foundation.org/
Wikipedia (en): https://en.wikipedia.org/wiki/Zammad
Source code: https://github.com/zammad/zammad

**Additional context**
Add any other context or screenshots about the app request here.

**Comment by steveiliop56** [comment]
Its too complicated to add...
