### ISSUE TITLE
[APP REQUEST] Lerntools

### ISSUE THREAD

**Issue by Lukas2112** [runtipi/runtipi-appstore#37]
**Describe app**

The "Lerntools" project reproduces many functions of Padlet, for example, but in a privacy-friendly, data-saving and open-source way. 

In addition, online surveys and ABCD questions can be created, as with Kahoot!

The advantage for runtipi users would be that they would get an accurate open source alternative to padlet.

**Links**
Project instance: https://lerntools.org/app/#/main-index
Source code: https://codeberg.org/lerntools

**Additional context**
Add any other context or screenshots about the app request here.

**Comment by steveiliop56** [comment]
It's not that popular to add...
