### ISSUE TITLE
[APP REQUEST] ArchiveBox

### ISSUE THREAD

**Issue by a2nr** [runtipi/runtipi-appstore#377]
Have you considered adding the app yourself? 
Yes, but I don't know how. 

**Describe app**
ArchiveBox is a powerful, self-hosted internet archiving solution to collect, save, and view sites you want to preserve offline.

**Links**
[ArchiveBox](https://github.com/ArchiveBox/ArchiveBox)

**Additional context**
following the documentation of installation archivebox using docker there is the first command to initialize the apps and it needs to fill some superuser configuration. the problem is I don't know how to bypass that using docker-compose/config.json on runtipi-appstore.
[Here](https://github.com/meienberger/runtipi-appstore/commit/97e177c5907477cfd93a9f1c3907f3ebd4ffe3a0) is my fork and commit. when I try to run it on runtipi doesn't show anything log on logs/app.

**Comment by hikeri** [comment]
You have an extra curly brace in your image.
The config is also outdated. It needs to be redone.

**Comment by meienberger** [comment]
Also the `config.json` cannot keep the comments from the example.

<img width="525" alt="Screenshot 2023-07-07 at 07 56 47" src="https://github.com/meienberger/runtipi-appstore/assets/47644445/4f699c29-7cec-40cf-ab31-e047a0aa30d8">

**Comment by steveiliop56** [comment]
Hello @a2nr, thank you for your submission, unfortunately this app is not maintained anymore...
