### ISSUE TITLE
[APP REQUEST] Sentry

### ISSUE THREAD

**Issue by mschadev** [runtipi/runtipi-appstore#47]
**Describe app**
> We’re so much more than error monitoring software. We’re also performance monitoring software. Our platform helps every developer diagnose, fix, and optimize the performance of their code. With Sentry, developers around the world save time, energy, and probably a few therapy sessions.
Sentry supports more than 30 coding languages, which means it probably supports yours. We also integrate with a whole bunch of useful tools (and a few necessary evils), including but definitely not limited to GitHub, Slack, and Jira.

**Links**
website: https://sentry.io
github org: https://github.com/getsentry
sentry self-hosted repository: https://github.com/getsentry/self-hosted
license: https://github.com/getsentry/self-hosted/blob/master/LICENSE
**Additional context**
Add any other context or screenshots about the app request here.

**Comment by steveiliop56** [comment]
Hello @mschadev, thank you for your request. Unfortunately this app requires a custom ``install.sh`` script that cannot be used by runtipi...
