### ISSUE TITLE
qbittorrent downgraded from 4.6.6 to 4.3.9

### ISSUE THREAD

**Issue by pokyunn** [runtipi/runtipi-appstore#4764]
Hi, this merge reverted qbittorrent to an old version 4.3.9 instead of current one 4.6.6

_Originally posted by @pokyunn in https://github.com/runtipi/runtipi-appstore/issues/4527#issuecomment-2327746424_

**Comment by meienberger** [comment]
Thank you @pokyunn opened #4822 to revert it
