### ISSUE TITLE
🐛 [Filebrowser] Unreachable via LAN IP since dynamic compose

### ISSUE THREAD

**Issue by DireMunchkin** [runtipi/runtipi-appstore#5373]
### Store Application

filebrowser

### App version

s6

### Description

After the merge of https://github.com/runtipi/runtipi-appstore/pull/5327 I cannot access Filebrowser over the LAN URL, I.E https://filebrowser.tipi.lan. The app starts normally and can be reached via host:port, but not the URL.

### Steps to reproduce

1. Update filebrowser to latest version.
2. Visit https://filebrowser.tipi.lan
3. 404 not found

### App logs

```bash
no relevant errors found in the logs AFAICT
```

### Browser

LibreWolf

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of RunTipi, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by DireMunchkin** [comment]
@Lancelot-Enguerrand This is your PR, could you have another look at it?

**Comment by meienberger** [comment]
Hello @DireMunchkin, with the new dynamic config you need to ensure the "Expose app on local network" option is checked in your settings. Make sure you have done so and restart the app

<img width="326" alt="Screenshot 2024-10-27 at 17 03 34" src="https://github.com/user-attachments/assets/0a27a0a5-427f-40fc-bfef-4c139337de8c">

**Comment by DireMunchkin** [comment]
Ah, right, that didn't use to be a setting before. Thanks for clarifying!
