### ISSUE TITLE
🐛 [Spacedrive] No support for arm64

### ISSUE THREAD

**Issue by al-lac** [runtipi/runtipi-appstore#5744]
### Store Application

Spacedrive

### App version

0.4.2

### Description

The app states there is support for arm64. But after installing it, nothing starts as it pulled the amd64 container on my arm vm.

### Steps to reproduce

1. Install Spacedrive
2. Try to open it
3. Check the logs

### App logs

```bash
spacedrive  | exec /usr/bin/entrypoint.sh: exec format error
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of RunTipi, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by meienberger** [comment]
Thanks for notifying us! I just updated the app to not show up anymore on arm64 installs
