### ISSUE TITLE
[APP REQUEST] Gluetun

### ISSUE THREAD

**Issue by RobotsAreCrazy** [runtipi/runtipi-appstore#613]
Gluetun VPN client

Lightweight swiss-knife-like VPN client to multiple VPN service providers

It's very useful for example for geo unblocking 

Source: https://github.com/qdm12/gluetun

Thankyou

**Comment by steveiliop56** [comment]
Hello @RobotsAreCrazy, thank you for your submission! Unfortunately this requires changing stuff in the docker compose file something that tipi cant do at the moment...

**Comment by meienberger** [comment]
Gluetun is not an app in itself, it is something you attach to your docker containers. You can try to use it by [customizing your app config](https://www.runtipi.io/docs/guides/customize-app-config)
