### ISSUE TITLE
[APP REQUEST] SHINOBI.VIDEO

### ISSUE THREAD

**Issue by Louisdulac59** [runtipi/runtipi-appstore#62]
Have you considered adding the app yourself?  i'm not able to do it myself

**Describe app**
An opensource CCTV solution

**Links**
https://shinobi.video/
https://gitlab.com/Shinobi-Systems/Shinobi

**Additional context**

**Comment by steveiliop56** [comment]
Hello @Louisdulac59, thank you for your submission, unfortunately this app requires the image to be built with docker something tipi can't do at the moment...
