### ISSUE TITLE
[APP REQUEST] Outline Wiki

### ISSUE THREAD

**Issue by 1itt1eB0y** [runtipi/runtipi-appstore#8]
**Describe app**
 A fast, collaborative, knowledge base for your team built using React and Node.js.

**Links**
https://github.com/outline/outline

**Comment by sethforprivacy** [comment]
Working on PRing this now.

**Comment by sethforprivacy** [comment]
Related docs, might take a stab at it when I have time: https://app.getoutline.com/s/770a97da-13e5-401e-9f8a-37949c19f97e/doc/docker-7pfeLP5a8t

**Comment by DrMxrcy** [comment]
This template can come complex, with no built-in auth and needings S3 Support Storage. I can take a stab at it, will have to figure out things like if I should deploy minio with it for local storage

**Comment by cygairko** [comment]
Meanwhile there's an example compose file available - not sure if that helps.
https://docs.getoutline.com/s/hosting/doc/docker-7pfeLP5a8t

**Comment by DrMxrcy** [comment]
> https://docs.getoutline.com/s/hosting/doc/docker-7pfeLP5a8t

Yes, the issue is choosing what auth provider to use by default. Its a more of a complex setup

**Comment by steveiliop56** [comment]
Ok this needs custom configuration with docker compose commands (see here https://docs.getoutline.com/s/hosting/doc/docker-7pfeLP5a8t) so we can't add it yet...

**Comment by hex-developer** [comment]
@1itt1eB0y I've added the app! Go test it and give me your feedback! Happy editing!
