### ISSUE TITLE
[APP REQUEST] - Quivr

### ISSUE THREAD

**Issue by codedbean** [runtipi/runtipi-appstore#868]
**Describe app**
Quivr, your second brain, utilizes the power of GenerativeAI to store and retrieve unstructured information. Think of it as Obsidian, but turbocharged with AI capabilities.

**Links**
https://github.com/StanGirard/quivr

**Additional context**
Dump all your files and chat with it using your Generative AI Second Brain using LLMs ( GPT 3.5/4, Private, Anthropic, VertexAI ) & Embeddings

**Comment by steveiliop56** [comment]
Hello @BotVue, thank you for your submission! Unfortunately this app requires building the images something tipi can't do at the moment...

**Comment by meienberger** [comment]
@BotVue Maybe you can add an issue to their repository to provide a docker image and we can re-open this issue
