### ISSUE TITLE
[APP REQUEST] - Noodle

### ISSUE THREAD

**Issue by BotVue** [runtipi/runtipi-appstore#869]
**Describe app**
Noodle is a platform that aims to solve this problem by providing a single platform for students to manage everything to do with their education. And with the power of having all of that data in one place, we can provide students with powerful insights and automation to help them be more productive.

**Links**
https://github.com/ixahmedxi/noodle

**Additional context**
![image](https://github.com/meienberger/runtipi-appstore/assets/51534682/bdcb7484-8425-43a7-9238-fe004f0b2b1e)

**Comment by steveiliop56** [comment]
Hello @BotVue,

Noodle would be an awesome idea for adding to the apostore and I have checked it myself too. But because it is still in development I wouldn't recommend adding yet. Have you tried installing it? Did it work?

**Comment by steveiliop56** [comment]
Yeah that would be awesome. Please try installing it (using docker of course) and post the results here.

**Comment by steveiliop56** [comment]
Hello @BotVue, unfortunately the app is still not stable so we can't add it right now...

**Comment by meienberger** [comment]
Indeed it seems to still be in a very unstable state. Let's keep an eye on it as it looks very useful
